# Generated by Django 3.2.5 on 2022-07-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220708_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(help_text='微信用户绑定和CC视频统计', max_length=64, unique=True),
        ),
    ]
